# Generated by Django 3.1 on 2020-08-24 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=55, verbose_name='Короткое наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=55, verbose_name='Версия')),
                ('date', models.DateField(verbose_name='Дата начала действия')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.reference')),
            ],
        ),
    ]
