# Generated by Django 3.1 on 2020-08-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200824_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='Версия')),
                ('date', models.DateField(verbose_name='Дата начала действия')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='ident',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='date',
        ),
        migrations.AlterField(
            model_name='reference',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.version'),
        ),
    ]
