# Generated by Django 3.1 on 2020-08-24 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200824_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала действия'),
        ),
        migrations.AddField(
            model_name='reference',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.reference', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='version',
            field=models.CharField(max_length=55, verbose_name='Версия'),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
